### ISSUE TITLE
Bringing back the Shorts-App

### ISSUE THREAD

**Issue by NeoTheThird** [doniks/shorter#4]
@ubports would like to bring the shorts app back as a preinstalled app on Ubuntu Touch.

Would you @doniks be interested to continue this apps development under the UBports umbrella?

**Comment by doniks** [comment]
Hey @NeoTheThird I think it'd be great to have Shorter preinstalled. I do indeed intend to continue development.

(That being said, it's a bit slow since I find Halium more exciting recently, and in combination with that, I don't have a running Ubports installation currently :-P )

**Comment by NeoTheThird** [comment]
> I think it'd be great to have Shorter preinstalled. I do indeed intend to continue development.

Awesome!

>  I find Halium more exciting recently

I get that :D 

> I don't have a running Ubports installation currently

How territorial are you about your work? If you want, we can fork it back to the ubports github organization crowd-source its development. That way you can work on it whenever you want and the development can still continue.

**Comment by doniks** [comment]
Well, I do draw some satisfaction from having resurrected the app. Of course I do understand that I'm standing on the shoulders of giants, like we all do. 

I could understand forking the app if I did a bad job as a maintainer. Or if you had so vast changes that you want to integrate and you think you can only ever really do that if you are the maintainer yourself. 

You might call it "territorial", but I don't think that is fair. I want the code and the app to strive. I'm very happy to look at any pull requests anyone might raise. And I do have some development ideas, but little time at the moment.

Let me raise another point that goes through my mind with this conversation: UBports is a small platform. Growing the population of independent app developers is one of the biggest challenges a platform faces in my perception. UBports should try to groom its independent app developers. Taking over maintainership of apps is pretty much the opposite behaviour.

**Comment by NeoTheThird** [comment]
Sorry, maybe that came out wrong. I didn't want to take away maintainership from you, i was just offering to host the repo on the ubports organization for better visibility. But you don't want that, and that's fine of course.

We will probably ship shorter pre-installed shorter in one of the upcoming releases, I will let you know.

Thanks for maintaining this nice app :)
